#!/usr/bin/env bash
# Daily promo: 06:30 WIB. If an article went live today (datePublished ==
# today in the content stores), generate a single same-day promo package on a
# dated branch and push it. Silent no-op (log only) when nothing went live.

. "$(dirname "$0")/lib.sh"

RUN_NAME="social daily promo"
LOG_FILE="$LOG_DIR/daily-$(date +%Y%m%d-%H%M%S).log"
exec >>"$LOG_FILE" 2>&1

TODAY=$(date +%Y-%m-%d)
BATCH_BRANCH="social/promo-$TODAY"

log "=== $RUN_NAME start ($TODAY) ==="
load_env
acquire_lock
arm_failure_trap

if git -C "$REPO" show-ref --quiet "refs/remotes/origin/$BATCH_BRANCH"; then
  log "origin already has $BATCH_BRANCH — nothing to do"
  release_lock; exit 0
fi

update_repo

# Which articles went live today? (see ops/live-today.js)
LIVE=$(node "$SCRIPT_DIR/live-today.js" "$REPO" "$TODAY")
log "live today: $LIVE"

if [ "$LIVE" = "[]" ]; then
  log "no article went live today — clean no-op"
  release_lock; exit 0
fi

ensure_chromelibs
make_worktree

node "$SOCIAL_DIR/harvest.js" --queue "$WT/tools/social/queue.json" | while read -r l; do log "harvest: $l"; done

PROMO_ID="promo-$TODAY"
MODE_FILE=$(mktemp)
{
  echo "## MODE"
  echo
  echo "DAILY promo. WEEK=$PROMO_ID. Write tools/social/weeks/$PROMO_ID.json."
  echo "Article(s) that went live today ($(date +'%A %Y-%m-%d')): $LIVE"
  echo "Pick ONE fact promoting one of these articles (targetPath must match)."
  echo "Use day 1 with date $TODAY. If no queue candidate belongs to these"
  echo "articles, write an empty facts array and change nothing else."
} > "$MODE_FILE"

run_claude "$MODE_FILE"
rm -f "$MODE_FILE"

WEEK_FILE="$WT/tools/social/weeks/$PROMO_ID.json"
[ -f "$WEEK_FILE" ] || { log "FATAL: claude did not write $WEEK_FILE"; false; }
FACT_COUNT=$(node -e 'console.log(require(process.argv[1]).facts.length)' "$WEEK_FILE")

if [ "$FACT_COUNT" -eq 0 ]; then
  log "no usable candidate for today's article(s) — clean no-op"
  cleanup_worktree
  release_lock; exit 0
fi

OUT_DIR="$WT/social-output/$PROMO_ID"
node "$SOCIAL_DIR/render.js" "$OUT_DIR" "$WEEK_FILE" | while read -r l; do log "render: $l"; done
node "$SOCIAL_DIR/packages.js" "$OUT_DIR" "$WEEK_FILE" | while read -r l; do log "packages: $l"; done
node "$SOCIAL_DIR/verify.js" "$WEEK_FILE" | while read -r l; do log "verify: $l"; done
assert_only_allowed_changes

git -C "$WT" add tools/social/weeks tools/social/queue.json "social-output/$PROMO_ID"
git -C "$WT" commit -q -m "social(promo): same-day promo for $TODAY launch

Generated by the unattended pipeline; figures verified verbatim against
the content stores by tools/social/verify.js before commit.

Co-Authored-By: Claude Fable 5 <noreply@anthropic.com>"
git -C "$WT" push -u origin "$BATCH_BRANCH" 2>&1 | while read -r l; do log "push: $l"; done

SUMMARY=$(batch_summary "$WEEK_FILE")
telegram_send "✅ ${RUN_NAME}: same-day package for today's launch

$SUMMARY

Review & merge:
$(compare_link)"

git -C "$REPO" worktree remove --force "$WT"; WT=""
log "=== done ==="
