#!/usr/bin/env bash
# Weekly batch: Sunday 20:00 WIB. Generates next week's 7 fact-card packages
# into social-output/<WEEK>/ on a dated branch and pushes it. The human gate
# stays: merge + schedule happen manually from the Telegram compare link.
#
# Usage: run-weekly.sh [--test]   (--test: branch social/test-e2e-<ts>,
#                                  message prefixed [E2E])

. "$(dirname "$0")/lib.sh"

TEST_MODE=false
[ "${1:-}" = "--test" ] && TEST_MODE=true

RUN_NAME="social weekly batch"
LOG_FILE="$LOG_DIR/weekly-$(date +%Y%m%d-%H%M%S).log"
exec >>"$LOG_FILE" 2>&1

# Next Monday..Sunday (run fires Sunday evening; "next monday" = tomorrow).
WEEK=$(date -d 'next monday' +%G-W%V)
if $TEST_MODE; then
  BATCH_BRANCH="social/test-e2e-$(date +%Y%m%d-%H%M%S)"
  RUN_NAME="[E2E] $RUN_NAME"
else
  BATCH_BRANCH="social/$WEEK"
fi

log "=== $RUN_NAME start (week $WEEK, branch $BATCH_BRANCH) ==="
load_env
acquire_lock
arm_failure_trap

if git -C "$REPO" show-ref --quiet "refs/remotes/origin/social/$WEEK" && ! $TEST_MODE; then
  log "origin already has social/$WEEK — nothing to do"
  release_lock
  exit 0
fi

update_repo
ensure_chromelibs

make_worktree

# Harvest fresh candidates inside the worktree (its queue.json is committed
# with the batch, so used-statuses persist once the branch merges).
node "$SOCIAL_DIR/harvest.js" --queue "$WT/tools/social/queue.json" | while read -r l; do log "harvest: $l"; done

# Mode block for the frozen prompt.
MODE_FILE=$(mktemp)
{
  echo "## MODE"
  echo
  echo "WEEKLY batch. WEEK=$WEEK. Write tools/social/weeks/$WEEK.json."
  echo "Posting dates:"
  for i in 0 1 2 3 4 5 6; do
    echo "- day $((i + 1)): $(date -d "next monday + $i days" +'%A %Y-%m-%d')"
  done
} > "$MODE_FILE"

run_claude "$MODE_FILE"
rm -f "$MODE_FILE"

WEEK_FILE="$WT/tools/social/weeks/$WEEK.json"
[ -f "$WEEK_FILE" ] || { log "FATAL: claude did not write $WEEK_FILE"; false; }
FACT_COUNT=$(node -e 'console.log(require(process.argv[1]).facts.length)' "$WEEK_FILE")
[ "$FACT_COUNT" -ge 1 ] || { log "FATAL: week file has no facts"; false; }
log "week file written: $FACT_COUNT fact(s)"

# Render + packages from the checkout's code (node_modules live there),
# facts + output in the worktree.
OUT_DIR="$WT/social-output/$WEEK"
node "$SOCIAL_DIR/render.js" "$OUT_DIR" "$WEEK_FILE" | while read -r l; do log "render: $l"; done
node "$SOCIAL_DIR/packages.js" "$OUT_DIR" "$WEEK_FILE" | while read -r l; do log "packages: $l"; done

# Gate: verbatim figures, direction rule, banned phrases, structure.
node "$SOCIAL_DIR/verify.js" "$WEEK_FILE" | while read -r l; do log "verify: $l"; done
assert_only_allowed_changes

git -C "$WT" add tools/social/weeks tools/social/queue.json "social-output/$WEEK"
git -C "$WT" commit -q -m "social($WEEK): weekly fact-card batch ($FACT_COUNT packages)

Generated by the unattended pipeline; every figure verified verbatim
against the content stores by tools/social/verify.js before commit.

Co-Authored-By: Claude Fable 5 <noreply@anthropic.com>"
git -C "$WT" push -u origin "$BATCH_BRANCH" 2>&1 | while read -r l; do log "push: $l"; done

SUMMARY=$(batch_summary "$WEEK_FILE")
telegram_send "✅ ${RUN_NAME}: $WEEK ready — $FACT_COUNT packages

$SUMMARY

Review & merge:
$(compare_link)"

git -C "$REPO" worktree remove --force "$WT"; WT=""
log "=== done ==="
